Error in download_doc profile id: 54231820 kiwi_profileid: 64973409 HTTPConnectionPool(host='mintglogm.monsterindia.com', port=80): Max retries exceeded with url: /103/M35/63274102/64973409/64973409.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B3A35EA5C0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) http://mintglogm.monsterindia.com/103/M35/63274102/64973409/64973409.txt
Error in download_doc profile id: 18208309 kiwi_profileid: 4402660 HTTPConnectionPool(host='mint10.monsterindia.com', port=80): Max retries exceeded with url: /95/M49/4886094/4402660/4402660.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020CDD017128>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',)) http://mint10.monsterindia.com/95/M49/4886094/4402660/4402660.txt
Error in download_doc profile id: 54231820 kiwi_profileid: 64973409 HTTPConnectionPool(host='mintglogm.monsterindia.com', port=80): Max retries exceeded with url: /103/M35/63274102/64973409/64973409.txt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x00000157D0B69F60>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed',)) http://mintglogm.monsterindia.com/103/M35/63274102/64973409/64973409.txt
Error in getLoginDetails : check_exist() missing 1 required positional argument: 'tableindex' []
Error in getLoginDetails : name 'm' is not defined []
Error in getLoginDetails : 2055: Lost connection to MySQL server at '10.216.247.119:3306', system error: 10038 An operation was attempted on something that is not a socket []
Error in getLoginDetails : 2003: Can't connect to MySQL server on '10.216.247.108:3306' (10060 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond) []
